#!/bin/sh

OPTS=" -o BatchMode=yes -o StrictHostKeyChecking=no -o ServerAliveInterval=30  -o ServerAliveCountMax=3 -o TCPKeepAlive=no -o ExitOnForwardFailure=yes "
KEY="/images/amxa/amxa-tunnel.key"
CONFIG="/images/amxa/amxa-tunnel.config"

if test "$1" = "--template"; then
    if ! test -e ${CONFIG}; then
cat <<EOF >${CONFIG}
# adapt these values to your needs
# remote must be unique!
REMOTE="5556"
HOST="backup.amxa.ch"
USER="tunnel"
PORT="443"
EOF
   fi
   exit 0
fi

if ! test "$1" = "--service"; then
    echo "usage: $(basename $0) [ --template | --service ]"
    exit 0
fi


if test -e ${KEY} -a -e ${CONFIG}; then
    chmod 600 ${KEY}
    . ${CONFIG}
    while true; do
	if ping -c 1  ${HOST} 2>/dev/null >/dev/null; then
            /usr/bin/autossh -M 0 -N -p ${PORT} -i ${KEY} ${OPTS} -R ${REMOTE}:localhost:22 ${USER}@${HOST}
        fi
	sleep 300
    done
else
    sleep 999999999
fi

exit
