#!/bin/sh

CONFIG="/images/amxa/amxa-tunnel.config"
FILE="/var/log/amxa-tunnel-ping.epoch"
MAXAGE="21600"

if test -f ${KEY} -a -f ${CONFIG}; then

. ${CONFIG}
    
   date +%s >$FILE
   echo "Start $(date)" >>/var/log/amxa-watchdog.log

   while true; do
      LAST="$(cat $FILE)"
      NOW="$(date +%s)"
      DIFF=$(( $NOW -$LAST ))
      if test "$DIFF" -gt $MAXAGE; then

	if ping -c 1  ${HOST} 2>/dev/null >/dev/null; then
           echo "Neustart $(date)" >>/var/log/amxa-watchdog.log
           systemctl stop amxa-tunnel
           sleep 60	
           systemctl start amxa-tunnel
           date +%s >$FILE
        fi
	
      fi
     sleep 3600
   done
else
    sleep 999999999
fi


exit
