Document: amxa-tunnel-service
Title: Debian amxa-tunnel-service Manual
Author: <insert document author here>
Abstract: This manual describes what amxa-tunnel-service is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amxa-tunnel-service/amxa-tunnel-service.sgml.gz

Format: postscript
Files: /usr/share/doc/amxa-tunnel-service/amxa-tunnel-service.ps.gz

Format: text
Files: /usr/share/doc/amxa-tunnel-service/amxa-tunnel-service.text.gz

Format: HTML
Index: /usr/share/doc/amxa-tunnel-service/html/index.html
Files: /usr/share/doc/amxa-tunnel-service/html/*.html
